apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus-py
  name: prometheus-py
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-py
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-py
    spec:
      containers:
      - image: prom-py:0.1
        name: prom-py
        resources: {}
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-py
  name: prometheus-py
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: prometheus-py
status:
  loadBalancer: {}

